import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import Navbar from "@/components/ui/navbar";
import "./globals.css";
import AuthLayout from "./context/AuthLayout";
import AuthContextProvider from "@/app/context/auth-context";
import { cookies } from "next/headers";


const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const getAccessToken = cookies().get('accessToken');
  const getAccessToken = cookies().get('accessToken')?.value ?? null;

  // // console.log(accessToken,"accessToken")


  const accessToken = getAccessToken// "accessToken";

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-gray-50 font-sans antialiased",
          fontSans.variable
        )}
      >
        <Navbar accessToken={accessToken}  />
        <AuthContextProvider accessToken={accessToken}>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
